// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function GetDownloadsDir() {
  return window['go']['main']['App']['GetDownloadsDir']();
}

export function GetNickname() {
  return window['go']['main']['App']['GetNickname']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SelectAndSendFile() {
  return window['go']['main']['App']['SelectAndSendFile']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
