// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string):Promise<string>;

export function Disconnect():Promise<void>;

export function DownloadFile(arg1:string):Promise<string>;

export function GetDownloadsDir():Promise<string>;

export function GetNickname():Promise<string>;

export function IsConnected():Promise<boolean>;

export function SelectAndSendFile():Promise<string>;

export function SendMessage(arg1:string):Promise<string>;
